using System.Collections.ObjectModel;

namespace Bingie.Services;

public record MotivationalQuote(string Text, string Author);

public static class QuotesService
{
    private static readonly ReadOnlyCollection<MotivationalQuote> Quotes = new(new List<MotivationalQuote>
    {
        new("Success is the sum of small efforts, repeated day in and day out.", "Robert Collier"),
        new("You don’t have to control your thoughts. You just have to stop letting them control you.", "Dan Millman"),
        new("Recovery is hard. Regret is harder.", "Brittany Burgunder"),
        new("You are stronger than your cravings.", "Anonymous"),
        new("Fall seven times, stand up eight.", "Japanese Proverb"),
        new("Every time you eat is an opportunity to nourish your body.", "Unknown"),
        new("The future depends on what you do today.", "Mahatma Gandhi"),
        new("Healing requires from us to stop struggling, but to enjoy life more and endure it less.", "Darina Stoyanova"),
        new("You don’t have to be perfect to be amazing.", "Unknown"),
        new("Each day provides its own gifts.", "Marcus Aurelius"),
        new("Focus on progress, not perfection.", "Bill Phillips"),
        new("Compassion is the radicalism of our time.", "Dalai Lama"),
        new("You were never created to live depressed, defeated, guilty, condemned, ashamed or unworthy. You were created to be victorious.", "Joel Osteen"),
        new("Your body is precious. It is your vehicle for awakening. Treat it with care.", "Buddha"),
        new("Small changes add up to big results.", "Unknown"),
        new("Believe you can and you're halfway there.", "Theodore Roosevelt"),
        new("You’re allowed to be both a masterpiece and a work in progress simultaneously.", "Sophia Bush"),
        new("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
        new("Starve the distractions, feed your focus.", "Unknown"),
        new("Every craving passes. Let this one go too.", "Anonymous"),
        new("I may not be there yet, but I’m closer than I was yesterday.", "Unknown"),
        new("You deserve a love that doesn’t make you question your worth.", "Unknown"),
        new("Act as if what you do makes a difference. It does.", "William James"),
        new("Healing is an art. It takes time. It takes practice. It takes love.", "Maza Dohta"),
        new("Don't let your mind bully your body.", "June Tomaso Wood"),
        new("Recovery is something that you have to work on every single day and it’s something that doesn’t get a day off.", "Demi Lovato"),
        new("You are allowed to reset. You are allowed to take a break.", "Unknown"),
        new("Eating well is a form of self-respect.", "Anonymous"),
        new("Sometimes the bravest and most important thing you can do is just show up.", "Brené Brown"),
        new("Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don’t belong.", "N.R. Narayana Murthy"),
        new("It always seems impossible until it’s done.", "Nelson Mandela"),
        new("Take care of your body. It’s the only place you have to live.", "Jim Rohn"),
        new("Courage doesn’t always roar. Sometimes it’s the quiet voice at the end of the day saying, “I will try again tomorrow.”", "Mary Anne Radmacher"),
        new("You are not a drop in the ocean. You are the entire ocean in a drop.", "Rumi"),
        new("Focus on how far you’ve come, not how far you have to go.", "Unknown"),
        new("Your past does not equal your future.", "Tony Robbins"),
        new("You can’t go back and change the beginning, but you can start where you are and change the ending.", "C.S. Lewis"),
        new("Progress is not linear, but it is progress.", "Unknown"),
        new("You have been criticizing yourself for years and it hasn’t worked. Try approving of yourself and see what happens.", "Louise Hay"),
        new("The comeback is always stronger than the setback.", "Unknown"),
        new("Recovery is about progression, not perfection.", "Unknown"),
        new("You are not weak because you need help.", "Unknown"),
        new("The best way out is always through.", "Robert Frost"),
        new("When eating is no longer a way to numb out, life can be overwhelming. Be gentle with yourself.", "Unknown"),
        new("Your worth is not measured by a plate.", "Anonymous"),
        new("One day or day one. You decide.", "Unknown"),
        new("Healing happens when you let the light in.", "Unknown"),
        new("You were given this life because you are strong enough to live it.", "Unknown"),
        new("The greatest wealth is health.", "Virgil"),
        new("What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"),
        new("Food is fuel, not a test of willpower.", "Unknown"),
        new("Nothing will work unless you do.", "Maya Angelou"),
        new("You don't have to see the whole staircase, just take the first step.", "Martin Luther King Jr."),
        new("Don’t wait until you’ve reached your goal to be proud of yourself. Be proud of every step you take toward reaching that goal.", "Simone Biles"),
        new("Gentleness with self is true strength.", "Unknown"),
        new("Every binge is a message. Listen, learn, and let it go.", "Anonymous"),
        new("The secret of getting ahead is getting started.", "Mark Twain"),
        new("Compassion for yourself is where the healing begins.", "Unknown"),
        new("You are built from courage you haven’t even met yet.", "Unknown"),
        new("Cravings are waves. Let them rise, let them fall.", "Anonymous"),
        new("Let food be the love letter you write to your body.", "Unknown"),
        new("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
        new("Your body hears everything your mind says. Stay kind.", "Unknown"),
        new("Every morning brings a fresh chance to align with your goals.", "Unknown"),
        new("Awareness is the first step to transformation.", "Eckhart Tolle"),
        new("Celebrate your small wins—they build to big victories.", "Unknown"),
        new("Even the darkest night will end and the sun will rise.", "Victor Hugo"),
        new("When you feel like quitting, remember why you started.", "Unknown"),
        new("One bite at a time, one moment at a time.", "Anonymous"),
        new("You can do anything for one day. Today is that day.", "Unknown"),
        new("Thoughts are not facts.", "Unknown"),
        new("Discomfort is temporary. Pride is permanent.", "Unknown"),
        new("You are not alone in this journey.", "Unknown"),
        new("Healthy looks different on everyone.", "Unknown"),
        new("Promise yourself to be so strong that nothing can disturb your peace of mind.", "Christian D. Larson"),
        new("Feed your mind with encouraging words and your body will follow.", "Unknown"),
        new("Hope is the only thing stronger than fear.", "Suzanne Collins"),
        new("Give yourself permission to start again.", "Unknown"),
        new("It’s not about being the best. It’s about being better than you were yesterday.", "Unknown"),
        new("Kindness changes everything—especially when aimed inward.", "Unknown"),
        new("You are enough just as you are.", "Meghan Markle"),
        new("One lap at a time is how you finish the marathon.", "Unknown"),
        new("Comfort yourself with care, not with punishment.", "Unknown"),
        new("Healing isn’t about controlling; it’s about letting go.", "Deborah Day"),
        new("The first wealth is health.", "Ralph Waldo Emerson"),
        new("You can’t hate your way into healing.", "Unknown"),
        new("Self-compassion is simply giving the same kindness to ourselves that we would give to others.", "Christopher Germer"),
        new("Never let success get to your head and never let failure get to your heart.", "Drake"),
        new("Your journey to wellness is uniquely yours.", "Unknown"),
        new("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
        new("You can rewrite your story at any meal.", "Unknown"),
        new("The only way to do great work is to love what you do.", "Steve Jobs"),
        new("Remember how far you’ve come, not just how far you have to go.", "Unknown"),
        new("Healing takes time, and asking for help is a courageous step.", "Mariska Hargitay"),
        new("The greatest step towards a life of simplicity is to learn to let go.", "Steve Maraboli"),
        new("The past is a place of reference, not a place of residence.", "Unknown"),
        new("What you resist persists. What you accept transforms.", "Unknown"),
        new("Consistency carves pathways that motivation alone can’t create.", "Unknown"),
        new("Your self-worth isn’t measured in calories.", "Unknown"),
        new("A calm mind brings inner strength and self-confidence.", "Dalai Lama"),
        new("Peace begins the moment you choose not to allow another person or event to control your emotions.", "Pema Chödrön"),
        new("Treat yourself as someone you are responsible for helping.", "Jordan Peterson"),
        new("Freedom begins the moment you realize you are not the voice in your head.", "Eckhart Tolle"),
        new("Health is a vehicle, not a destination.", "Joshua Fields Millburn"),
        new("Promise yourself you will not quit.", "Unknown"),
        new("Recovery is the acceptance that your life is in shambles and you have to change it.", "Jamie Lee Curtis"),
        new("You are not a before picture. You are a living, breathing masterpiece now.", "Unknown"),
        new("Let your choices be guided by love, not fear.", "Unknown"),
        new("Your transformation is built on the tiny decisions you make today.", "Unknown"),
        new("The sun will rise and we will try again.", "Twenty One Pilots"),
        new("Strength grows in the moments when you think you can’t go on but you keep going anyway.", "Unknown"),
        new("Feelings are just visitors. Let them come and go.", "Mooji"),
        new("You are still deserving of good things while you’re trying to become better.", "Morgan Harper Nichols"),
        new("If it costs you your peace, it’s too expensive.", "Unknown"),
        new("You can’t live a positive life with a negative mind.", "Joyce Meyer"),
        new("The greatest healing therapy is friendship and love.", "Hubert H. Humphrey"),
        new("There is hope, even when your brain tells you there isn’t.", "John Green"),
        new("Let gratitude be the pillow upon which you kneel to say your nightly prayer.", "Maya Angelou"),
        new("Ease is a greater threat to progress than hardship.", "Denzel Washington"),
        new("You are the sky. Everything else is just the weather.", "Pema Chödrön"),
        new("Your pace is perfect for your journey.", "Unknown"),
        new("Take time to do things that make you feel alive.", "Unknown"),
        new("Hold yourself to a standard of grace, not perfection.", "Unknown"),
        new("Great things are done by a series of small things brought together.", "Vincent van Gogh"),
        new("The body achieves what the mind believes.", "Unknown"),
        new("Trust the process. You are blooming.", "Unknown"),
        new("Today I will love myself enough to nourish my body.", "Unknown"),
        new("Healing is not a destination; it’s a way of life.", "Unknown"),
        new("When you replace 'why is this happening to me' with 'what is this trying to teach me,' everything shifts.", "Unknown"),
        new("Repeat after me: My worth is not tied to my eating.", "Unknown"),
        new("Discipline is remembering what you want.", "David Campbell"),
        new("You don’t drown by falling in the water; you drown by staying there.", "Edwin Louis Cole"),
        new("My body deserves respect. My heart deserves kindness.", "Unknown")
    });

    public static MotivationalQuote GetRandomQuote(Random? random = null)
    {
        var rng = random ?? Random.Shared;
        return Quotes[rng.Next(Quotes.Count)];
    }

    public static IReadOnlyList<MotivationalQuote> GetAllQuotes() => Quotes;
}
